### PR TITLE
Bookings/new

### PR DESCRIPTION
**Pull request by hankhng**
1. Reformatted date picker. It is now a range again. In order for it to be a range, it has to be in string format. So will discuss tomorrow whether to convert the data type to 'string' in schema again.

2. Scooters/1/bookings/new now works. However needs styling formatting. (WIP)

3. After completing booking from step 2 above, Bookings/:id now works. Need some formatting also (WIP).

4. Added some placeholder images to bookings/index. Need to update them with cl image_tags eventually when we have cloudinary up and running.

#2 image

#3 image

#4 image

### CODE REVIEW

**Comment by hankhng** [comment]
[Bookings/New](https://trello.com/c/Gj3DL1Bw/24-bookings-new)

**Comment by thomasvanholder** [comment]
Awesome @hank!
Let's work on the styling today.

**Comment by hankhng** [comment]
Yep definitely! Will create a new branch to work on the styling today @thomasvanholder :)

**Comment by hank** [comment]
> Awesome @hank!
> Let's work on the styling today.

*sigh*

**Pull request merged**
